apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gfzxbvpaq-python
  janus-idp.io/tekton: gfzxbvpaq-python
  backstage.io/kubernetes-id: gfzxbvpaq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfzxbvpaq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
